version: '3.8'

services:
  # БД
  db:
    image: postgres:15-alpine
    container_name: furniture_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - furniture_network

  # Django приложение
  web:
    build: .
    container_name: furniture_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - furniture_network

  # Nginx веб-сервер
  nginx:
    image: nginx:alpine
    container_name: furniture_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    ports:
      - "80:80"
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - furniture_network

# Volumes 
volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  furniture_network:
    driver: bridge